export const INIT_QUESTION = 'INIT_QUESTION';
export const QUES_CHANGER = 'QUES_CHANGER';
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const RES_FINAL = 'RES_FINAL';
export const RES_CHANGER = 'RES_CHANGER';
export const CORRECT_OPTION = 'CORRECT_OPTION';
export const VIDEO_CHANGER = "VIDEO_CHANGER";
export const INIT_VIDEO = "INIT_VIDEO";